class_name ItemView3D
extends Node3D
## Lightweight animated Sprite3D pickup generated by ImageGen.

const TARGET_CELL_WIDTH := 0.84

var item_id: int
var item_type: int

var _sprite: Sprite3D
var _base_height: float = 0.04
var _elapsed: float = 0.0


func setup(item: ArenaItemState) -> void:
	item_id = item.item_id
	item_type = item.item_type
	name = "ArenaItem%d" % item_id
	position = GameConstants.grid_to_world_3d(item.cell, _base_height)
	_build_visual()


func _process(delta: float) -> void:
	_elapsed += delta
	if is_instance_valid(_sprite):
		_sprite.rotation.z = sin(_elapsed * 2.1 + float(item_id)) * 0.09
		_sprite.position.y = _sprite_height() + sin(
			_elapsed * 2.8 + float(item_id)
		) * 0.07


func _build_visual() -> void:
	var texture := load(ArenaItemType.texture_path(item_type)) as Texture2D
	_sprite = Sprite3D.new()
	_sprite.name = "ImageGenPickupSprite"
	_sprite.texture = texture
	_sprite.pixel_size = _pixel_size(texture)
	_sprite.position.y = _sprite_height()
	StorybookMaterialLibrary.configure_billboard(_sprite)
	add_child(_sprite)

	var ring := MeshInstance3D.new()
	ring.name = "PickupRing"
	var ring_mesh := TorusMesh.new()
	ring_mesh.inner_radius = 0.34
	ring_mesh.outer_radius = 0.43
	ring_mesh.rings = 12
	ring_mesh.ring_segments = 24
	ring.mesh = ring_mesh
	ring.position.y = 0.01
	ring.material_override = StorybookMaterialLibrary.make(
		ArenaItemType.accent_color(item_type),
		0.88,
		false,
		0.12
	)
	ring.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	add_child(ring)


func get_visual_cell_width() -> float:
	if not is_instance_valid(_sprite) or _sprite.texture == null:
		return 0.0
	var image := _sprite.texture.get_image()
	if image == null:
		return 0.0
	return float(image.get_used_rect().size.x) * _sprite.pixel_size


func _pixel_size(texture: Texture2D) -> float:
	if texture == null:
		return 0.0022
	var image := texture.get_image()
	if image == null:
		return TARGET_CELL_WIDTH / float(maxi(texture.get_width(), 1))
	var visible_width := maxi(image.get_used_rect().size.x, 1)
	return TARGET_CELL_WIDTH / float(visible_width)


func _sprite_height() -> float:
	if not is_instance_valid(_sprite) or _sprite.texture == null:
		return 0.3
	return float(_sprite.texture.get_height()) * _sprite.pixel_size * 0.48
